[package]
name = "vike-example"
edition = "2024"
version = "0.1.0"

[dependencies]
winit = { workspace = true }
image = { workspace = true }
futures-lite = { workspace = true }
vike = { path = "../vike" }
env_logger = "0.10"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
