[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "target-feature=+simd128,+atomics,+bulk-memory,+mutable-globals",
  "-C", "opt-level=z",
  "-C", "codegen-units=1",
  "-C", "panic=abort",
  "-Z", "location-detail=none",
]

[unstable]
build-std = ["panic_abort", "std"]